---
# This playbook contains common plays that will be run on all nodes.

- name: Install some core packages
  yum: name={{ item }} state=present
  with_items:
   - nfs-utils
   - git
   - libsemanage-python
   - libselinux-python
   - ntp
   - nano

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntpd state=started enabled=true
  tags: ntp

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
