---
# These tasks install http and the php modules.

- name: Install repos
  shell: rpm -Uvh --force {{ item }}
  with_items:
   - http://download.fedoraproject.org/pub/epel/6/i386/epel-release-6-8.noarch.rpm
   - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

- name: Install Yum packages
  yum: name={{ item }} state=present
  with_items:
   - rubygems

- name: Install Apache and PHP
  yum: name={{ item }} state=present enablerepo=remi,remi-php55
  with_items:
   - httpd
   - php
   - php-common
   - php-cli
   - php-gd
   - php-mbstring
   - php-mcrypt
   - php-mysql
   - php-pdo
   - php-pear
   - php-pecl-apc
   - php-xdebug
   - php-xml

- name: Install Node and npm
  yum: name={{ item }} state=present enablerepo=epel
  with_items:
   - nodejs
   - npm

- name: Install Node packages
  npm: name={{ item }} global=yes
  with_items:
   - uglify-js

# @todo: Can't get the gem module to work properly!
- name: Install Ruby packages
  command: gem install {{ item }} creates=/usr/local/bin/{{ item }}
  with_items:
   - chunky_png
   - fssm
   - sass
   - compass

- name: Create vhost configuration file
  template: src=vhost.conf dest=/etc/httpd/conf/vhost.conf

- name: Include vhost.conf from httpd.conf
  lineinfile:
    dest=/etc/httpd/conf/httpd.conf
    line="Include /etc/httpd/conf/vhost.conf"
    state=present
    insertafter=EOF

- name: Change http user and group to vagrant
  shell: sed -i 's/{{ item }} apache/{{ item }} vagrant/g' /etc/httpd/conf/httpd.conf
  with_items:
   - User
   - Group
  notify: restart httpd

- name: insert iptables rule for httpd
  lineinfile: dest=/etc/sysconfig/iptables-config create=yes state=present regexp="{{ httpd_port }}" insertafter="^:OUTPUT "
              line="-A INPUT -p tcp  --dport {{ httpd_port }} -j  ACCEPT"
  notify: restart iptables

- name: http service state
  service: name=httpd state=started enabled=yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean: name=httpd_can_network_connect_db state=true persistent=yes 
  when: sestatus.rc != 0

- name: Install composer
  shell:
    curl -sS https://getcomposer.org/installer | /usr/bin/php && /bin/mv -f /home/vagrant/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer

- name: Composer install app
  command: chdir=/vagrant composer install --prefer-source --dev creates=/vagrant/composer.lock

- name: Composer update
  command: chdir=/vagrant composer update